# Generated by Django 5.0.1 on 2024-01-27 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_contactme_project_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experience',
            new_name='Skills',
        ),
    ]
