# Generated by Django 5.0.1 on 2024-01-27 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_experience_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name_plural': 'Skills'},
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='company_name',
            new_name='skill_image',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='job_title',
            new_name='skill_name',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='duty',
        ),
    ]
