# Generated by Django 5.0.1 on 2024-08-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0007_contactme_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactme",
            name="first_name",
            field=models.CharField(default="First name", max_length=100),
        ),
        migrations.AddField(
            model_name="contactme",
            name="last_name",
            field=models.CharField(default="Last name", max_length=100),
        ),
    ]
