# Generated by Django 5.0.1 on 2024-08-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0008_contactme_first_name_contactme_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactme",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="contactme",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="contactme",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
    ]
