# Generated by Django 4.2.16 on 2024-09-04 09:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_contactme_email_alter_contactme_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='summary',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='intro',
            field=ckeditor.fields.RichTextField(default='Hi there...'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
