# Generated by Django 4.2.16 on 2024-09-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_about_summary_alter_dashboard_intro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tech_stack',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='Personal Project', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(default='Tech Lead', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='team_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
