# Generated by Django 4.2.16 on 2024-09-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_blog_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_closure',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog_intro',
        ),
    ]
